### ISSUE TITLE
laravel 7 config issue, array_merge(): Expected parameter 2 to be an array, object given

### ISSUE THREAD

**Issue by djelusive** [smalot/pdfparser#339]
Using Laravel 7, after installing pdfparser using composer successfully and then clearing the config cache, it returns with:
array_merge(): Expected parameter 2 to be an array, object given for: /vendor/smalot/pdfparser/src/Smalot/PdfParser/RawData/RawDataParser.php line 67.
```
    public function __construct($cfg = [])
    {
        // merge given array with default values
        
        $this->cfg = array_merge($this->cfg, $cfg);
        $this->filterHelper = new FilterHelper();
    }
```
Could I have some assistance understanding why this would be the case?

```
[2020-09-17 07:38:42] local.ERROR: array_merge(): Expected parameter 2 to be an array, object given {"exception":"[object] (ErrorException(code: 0): array_merge(): Expected parameter 2 to be an array, object given at /var/www/html/db/vendor/smalot/pdfparser/src/Smalot/PdfParser/RawData/RawDataParser.php:67)
[stacktrace]
#0 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'array_merge(): ...', '/var/www/html/d...', 67, Array)
#1 /var/www/html/db/vendor/smalot/pdfparser/src/Smalot/PdfParser/RawData/RawDataParser.php(67): array_merge(Array, Object(Illuminate\\Foundation\\Application))
#2 /var/www/html/db/vendor/smalot/pdfparser/src/Smalot/PdfParser/Parser.php(58): Smalot\\PdfParser\\RawData\\RawDataParser->__construct(Object(Illuminate\\Foundation\\Application))
#3 /var/www/html/db/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php(208): Smalot\\PdfParser\\Parser->__construct(Object(Illuminate\\Foundation\\Application))
#4 /var/www/html/db/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php(144): Illuminate\\Foundation\\ProviderRepository->createProvider('Smalot\\\\PdfParse...')
#5 /var/www/html/db/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php(61): Illuminate\\Foundation\\ProviderRepository->compileManifest(Array)
#6 /var/www/html/db/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(604): Illuminate\\Foundation\\ProviderRepository->load(Array)
#7 /var/www/html/db/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/RegisterProviders.php(17): Illuminate\\Foundation\\Application->registerConfiguredProviders()
#8 /var/www/html/db/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(230): Illuminate\\Foundation\\Bootstrap\\RegisterProviders->bootstrap(Object(Illuminate\\Foundation\\Application))
#9 /var/www/html/db/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\\Foundation\\Application->bootstrapWith(Array)
#10 /var/www/html/db/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(135): Illuminate\\Foundation\\Http\\Kernel->bootstrap()
#11 /var/www/html/db/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(109): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#12 /var/www/html/db/public/index.php(55): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#13 {main}
"} ```

Resolved:
I had added the Parser as a service provider class. For some reason Laravel did not like this. After removing it as a service provider not only did the parser start working, but I could clear my config cache successfully.

**Comment by k00ni** [comment]
Can you please post the full stack trace, if available?

**Comment by k00ni** [comment]
Thank you for the feedback.
