### ISSUE TITLE
iconv(): Wrong encoding, conversion from "CP1252" to "UTF-8" is not allowed

### ISSUE THREAD

**Issue by f-wehrhausen** [smalot/pdfparser#538]
Hey,

if after I parse the pdf and use the ->getText() - function it throws the following exception:

`iconv(): Wrong encoding, conversion from "CP1252" to "UTF-8" is not allowed`

I have found a similar problem already here only it is now with me another initial encoding (CP1252):
https://github.com/smalot/pdfparser/issues/229 

Can someone help me to find a solution?

**Comment by RitzenthalerF** [comment]
Hi,
Has there been any update or a workaround for this problem?
I'm getting the same error for quite a few of the files I'm trying to process, either the CP1252 or the Macintosh message.

Thanks in advance for your help,
Frederik

**Comment by k00ni** [comment]
@RitzenthalerF please try, if @f-wehrhausen's code change helps. If so, we could add a switch as suggested.

CC @j0k3r @izabala @Connum Is that switch-idea silly or could it work? This change could be a pull request candidate.

**Comment by RitzenthalerF** [comment]
@k00ni : Checked it out, it seems fine for the CP1252 but throws another error for the Macintosh format. (to be honest, I have only one Mac-created PDf at hand for now, so I don't claim that this is representative ;)

Fatal error: Uncaught ValueError: mb_convert_encoding(): Argument #3 ($from_encoding) contains invalid encoding "MACINTOSH" in /web/vendor/smalot/pdfparser/src/Smalot/PdfParser/Font.php:605 Stack trace: #0 /web/vendor/smalot/pdfparser/src/Smalot/PdfParser/Font.php(605): mb_convert_encoding() #1 /web/vendor/smalot/pdfparser/src/Smalot/PdfParser/Font.php(553): Smalot\PdfParser\Font->decodeContentByEncodingElement() #2 /web/vendor/smalot/pdfparser/src/Smalot/PdfParser/Font.php(467): Smalot\PdfParser\Font->decodeContentByEncoding() #3 /web/vendor/smalot/pdfparser/src/Smalot/PdfParser/Font.php(449): Smalot\PdfParser\Font->decodeContent() #4 /web/vendor/smalot/pdfparser/src/Smalot/PdfParser/PDFObject.php(341): Smalot\PdfParser\Font->decodeText() #5 /web/vendor/smalot/pdfparser/src/Smalot/PdfParser/Page.php(218): Smalot\PdfParser\PDFObject->getText() #6 /web/vendor/smalot/pdfparser/src/Smalot/PdfParser/Document.php(277): Smalot\PdfParser\Page->getText() #7 /web/Classes/PDF_ext/parse_pdf_funkcio.php(12): Smalot\PdfParser\Document->getText() #8 /web/feltolt_api.php(121): pdf_parser() #9 {main} thrown in /web/vendor/smalot/pdfparser/src/Smalot/PdfParser/Font.php on line 605

Thank you :)

**Comment by j0k3r** [comment]
Well I don't know if we wont have other issue with Mac encoding if we switch back to `mb_convert_encoding` instead of `iconv`.

**Comment by k00ni** [comment]
Would it help if we extend our `Config` class with a Mac-mode (default = off) and use functions, which work better with Mac related PDFs?

**Comment by j0k3r** [comment]
It could be an idea but I'm not sure if people will 100% sure that they will never/always convert Mac related PDFs

**Comment by ephrin** [comment]
Reproduced on linux build of PHP. File generated by PDFLib

**Comment by AndreySlashman** [comment]
@ephrin sorry for pinging but did you manage to find the file? :)

**Comment by jmazier-j2d** [comment]
Having the same issue but with MACINTOSH encoding. We'll give a try to @f-wehrhausen modification and add a switch.

On my end, the error is : `ErrorException: iconv(): Wrong encoding, conversion from "MACINTOSH" to "UTF-8//TRANSLIT//IGNORE" is not allowed`

**Comment by jholthusen** [comment]
Any updates on this? Basically, it looks like a switch based on $iconvEncodingName might be a way to address this. For my pdf, the change by @f-wehrhausen works for CP1252 - based files (which will be the majority in my use case).

**Comment by sharma-ss** [comment]
@f-wehrhausen , did you find any solution for the same ?

**Comment by ephrin** [comment]
@AndreySlashman , @GreyWyvern
sorry for delay guys.
 we moved out from the distribution of the OS (debian wheezy) and it is gone
