### ISSUE TITLE
Fatal Error: Uncaught TypeError on decodeXrefStream

### ISSUE THREAD

**Issue by juneyeeleow** [smalot/pdfparser#605]
- PHP Version: 7.2.34
 - PDFParser Version: 2.5

### Description:
There is a PDF that will cause this fatal error.
I can't share that PDF without consent from client.

### Expected output & actual output
PHP Notice:  Undefined offset: 1 in /var/www/APIHOME/src/vendor/smalot/pdfparser/src/Smalot/PdfParser/RawData/RawDataParser.php on line 890
PHP Fatal error:  Uncaught TypeError: Argument 2 passed to Smalot\PdfParser\RawData\RawDataParser::decodeXrefStream() must be of the type integer, null given, called in /var/www/APIHOME/src/vendor/smalot/pdfparser/src/Smalot/PdfParser/RawData/RawDataParser.php on line 905 and defined in /var/www/APIHOME/src/vendor/smalot/pdfparser/src/Smalot/PdfParser/RawData/RawDataParser.php:236
Stack trace:
#0 /var/www/APIHOME/src/vendor/smalot/pdfparser/src/Smalot/PdfParser/RawData/RawDataParser.php(905): Smalot\PdfParser\RawData\RawDataParser->decodeXrefStream('%PDF-1.3\r\n%\xFF\xFF\xFF\xFF...', NULL, Array)
#1 /var/www/APIHOME/src/vendor/smalot/pdfparser/src/Smalot/PdfParser/RawData/RawDataParser.php(216): Smalot\PdfParser\RawData\RawDataParser->getXrefData('%PDF-1.3\r\n%\xFF\xFF\xFF\xFF...', 5623273, Array)
#2 /var/www/APIHOME/src/vendor/smalot/pdfparser/src/Smalot/PdfParser/RawData/RawDataParser.php(902): Smalot\PdfParser\RawData\RawDataParser->decodeXref('%PDF-1.3\r\n%\xFF\xFF\xFF\xFF...', 178, Array)
#3 /var/www/APIHOME/src/vendor/sm in /var/www/APIHOME/src/vendor/smalot/pdfparser/src/Smalot/PdfParser/RawData/RawDataParser.php on line 236

### Code
$pdf  = $parser->parseFile('patch_to_file');

**Comment by juneyeeleow** [comment]
[Appraisal_20230608015CC_V1.PDF](https://github.com/smalot/pdfparser/files/11761256/Appraisal_20230608015CC_V1.PDF)
